GET {{FiMAdminApi_HostAddress}}/api/v1.0/users
Accept: application/json
Authorization: Bearer {{ Token }}

###

POST {{FiMAdminApi_HostAddress}}/api/v1/events-create/sync-source
Accept: application/json
Authorization: Bearer {{ Token }}
Content-Type: application/json

{
  "overrideExisting": true,
  "seasonId": 1,
  "dataSource": "FrcEvents",
  "districtCode": null,
  "eventCodes": [
    "CODEN"
  ]
}

###

