using Asp.Versioning.Builder;
using FiMAdminApi.Models.Enums;
using FiMAdminApi.Services;
using Microsoft.AspNetCore.Mvc;

namespace FiMAdminApi.Endpoints;

public static class ThumbnailEndpoints
{
    public static WebApplication RegisterThumbnailEndpoints(this WebApplication app, ApiVersionSet vs)
    {
        var routeGroup = app.MapGroup("/api/v{apiVersion:apiVersion}/thumbnail")
            .WithApiVersionSet(vs).HasApiVersion(1).WithTags("Thumbnails")
            .RequireAuthorization(nameof(GlobalPermission.Equipment_Av_ManageStream));

        routeGroup.MapGet("", GetThumbnail)
            .WithSummary("Generate a thumbnail PNG for testing")
            .WithDescription("Returns a PNG thumbnail generated by the server using the ThumbnailService. Query parameters: programType (FRC|FTC), line1, line2, line3.");

        return app;
    }

    private static async Task<IResult> GetThumbnail(
        [FromServices] ThumbnailService thumbnailService,
        [FromQuery] string? programType,
        [FromQuery] string? line1,
        [FromQuery] string? line2,
        [FromQuery] string? line3)
    {
        try
        {
            var bytes = await thumbnailService.DrawThumbnailAsync(programType ?? "FRC", line1, line2, line3);
            return Results.File(bytes, "image/png");
        }
        catch (Exception ex)
        {
            return Results.Problem(ex.Message);
        }
    }
}
